### ISSUE TITLE
[BUG] assignment 2024-001 - deciding_depot_location.ipynb and yamls files were considered not expected

### ISSUE THREAD

**Issue by r4b61t** [UCL-COMP0233-24-25/assignment-submission-checker#13]
## Description

Using the assignment checker on the assignment 2024-001 gives the following warnings
```
The following files were found in depot_locations, but were not expected:
		deciding_depot_location.ipynb
	
The following files were found in data, but were not expected:
		bad_location_inputs.yaml
		capitalisation_fixtures.yaml
		bad_location_values.yaml
		travel_time_fixtures.yaml
		distance_fixtures.yaml
		location_example.yaml
```
- The notebook file that was included with the providedCode.zip has different name to the one in the spec.
- The spec also prevents using any other data types other than .csv for testing purposes. I am not sure if this is intentional but it prevents us from using yaml for storing pytest fixtures. 

## Minimal Steps to Reproduce

- create a file name `deciding_depot_location.ipynb` in the root directory.
- create one or more `.yaml` file in the `data/` directory
- run `assignment-checker 2024-001 ./depot_locations`

## Desired Outcome
There should not be warning regarding `deciding_depot_location.ipynb` and `*.yaml` files being unexpected

**Comment by willGraham01** [comment]
Closed in #14
